app/blueprints/table/__init__.py
from flask import Blueprint

# Create the blueprint instance
table_bp = Blueprint('table',
                     __name__,
                     template_folder='templates',
                     static_folder='static',
                     static_url_path='/table/static')

# Import the routes module
from . import routes

app/blueprints/table/routes.py
from flask import render_template, send_from_directory, current_app
from . import table_bp
from models import Paper


# Define routes and views
@table_bp.route('/')
def index():
    papers = Paper.objects().order_by('-year')
    return render_template('table/index.html', data=papers)


@table_bp.route('/certificate/<path:certificate>/', methods=['GET'])
def download_certificate(certificate):
    return send_from_directory(current_app.config["UPLOAD_FOLDER"], certificate, as_attachment=True)

app/blueprints/table/templates/table/index.html
{% extends 'base.html' %}

{% block styles %}
    <!-- Datatable -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="{{url_for('table.static', filename='css/datatable.css')}}" />

    <!-- Boostrap for Datatable styling -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css" />
    

    <!-- Country flag-icons CSS-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flag-icon-css/css/flag-icon.min.css">
{% endblock %}

{% block content %}
    <!-- <input class="form-control" id="myInput" type="text" placeholder="Search.."> -->
    <table class="hover compact order-column" id="bpa_table">
        <thead>
            {% block table_header %}
                <tr>
                    {% include 'table/table_columns.html' %}
                </tr>
            {% endblock %}
        </thead>
        <tbody>
            {% block table_content %}
                {% for paper in data %}
                <tr>
                    {% with paper=paper %}
                        {% include 'table/table_rows.html' %}
                    {% endwith %}
                </tr>
                {% endfor %}
            {% endblock %}
        </tbody>
        <tfoot>
            {% block table_footer %}
                <tr>
                    {% include 'table/table_columns.html' %}
                </tr>
            {% endblock %}
        </tfoot>
    </table>
{% endblock %}

{% block scripts %}
    <!-- Datatable -->
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>

    <script src="{{url_for('table.static', filename='js/datatable.js')}}"></script>
    

    <!-- Boostrap for Datatable styling -->
    <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
{% endblock %}
    

app/blueprints/table/templates/table/table_columns.html
<th title="Conference">Venue</th>
<th title="Year of publication">Year</th>
<th title="DOI/URL of the paper">DOI</th>
<th title="DOI/URL of the extended (journal) version">Ext.</th>
<th title="Paper's title">Title</th>
<th title="Paper's authors">Authors</th>
<th title="Authors' affiliations">Affiliations</th>
<th><i class="fa-solid fa-earth-europe" style="color: black;" title="Affiliations' countries"></i><span hidden>Countries</span></th>
<th title="Award's title">Award</th>
<th><i class="fa-solid fa-award" style="color: black;" title="Certificate of the best paper award"></i><span hidden>Certificate</span></th>
<th><i class="fa-solid fa-circle-check" style="color: black;" title="Verified"><span hidden>Verified</span></th>

app/blueprints/table/templates/table/table_rows.html
<td>{{paper.venue if paper.venue}}</td>
<td>{{paper.year if paper.year}}</td>
<td><a href="{{paper.doi}}" title="Paper"><i class="fa-regular fa-file-lines" style="color: black;"></i></a><span hidden>{{paper.doi}}</span></td>
<td>{% if paper.extended_doi %}<a href="{{paper.extended_doi}}" title="Extended (journal) version"><i class="fa-solid fa-file-lines" style="color:black;"></i></a><span hidden>{{paper.extended_doi}}</span>{% endif %}</td>
<td>{{paper.title if paper.title }}</td>
<td>{{paper.authors | join(', ')}}</td>
<td>{{paper.affiliations | join (', ')}}</td>
<td>{% for country in paper.countries %}<i class="flag-icon flag-icon-{{country.code}}" title={{country.name}}><span hidden>{{country.name}}</span></i>{% endfor %}</td>
<td>{{ paper.award if paper.award }}</td>
<td>{% if paper.certificate %}<a href="{{ url_for('table.download_certificate', certificate=paper.certificate) }}" title="Download certificate"><i class="fa-solid fa-award" style="color: goldenrod;"></i></a><span hidden>{{paper.certificate}}</span>{% endif %}</td>
<td>{% if paper.verified %}<i class="fa-solid fa-circle-check" style="color: green;" title="This award has been verified."></i><span hidden>True</span>{% else %}<i class="fa-solid fa-circle-minus" style="color: grey;" title="This award is unverified."></i><span hidden>False</span>{% endif %}</td>